config/routes.rb
Rails.application.routes.draw do


  resources :payments
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :goals
  resources :users do
    # resources :bank_payments
    resources :payments
    resources :pictures
  end

  root 'home#index'
  get 'testpage', to: 'home#tester'
  get 'new_bank_info', to: 'users#edit'
end

app/models/bank_payment.rb
class BankPayment < ApplicationRecord
  belongs_to :user
end

app/controllers/bank_payments_controller.rb
class BankPaymentsController < ApplicationController
  before_action :set_bank_payment, only: [:show, :edit, :update, :destroy]

  # GET /bank_payments
  # GET /bank_payments.json
  def index
    @bank_payments = BankPayment.all
  end

  # GET /bank_payments/1
  # GET /bank_payments/1.json
  def show
  end

  # GET /bank_payments/new
  def new
    @bank_payment = BankPayment.new
  end

  # GET /bank_payments/1/edit
  def edit
  end

  # POST /bank_payments
  # POST /bank_payments.json
  def create
    @bank_payment = BankPayment.new(bank_payment_params)

    @bank_payment.user = current_user

    respond_to do |format|
      if @bank_payment.save
        format.html { redirect_to current_user, notice: 'Bank payment was successfully created.' }
        format.json { render :show, status: :created, location: @bank_payment }
      else
        format.html { render :new }
        format.json { render json: @bank_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_payments/1
  # PATCH/PUT /bank_payments/1.json
  def update
    respond_to do |format|
      if @bank_payment.update(bank_payment_params)
        format.html { redirect_to root_path, notice: 'Bank payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_payment }
      else
        format.html { render :edit }
        format.json { render json: @bank_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_payments/1
  # DELETE /bank_payments/1.json
  def destroy
    @bank_payment.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Bank payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_payment
      @bank_payment = BankPayment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_payment_params
      params.require(:bank_payment).permit(:pull_bank_account, :pull_bin, :debit_exp, :currency_code, :amount, :pull_name, :pull_address, :transaction_time, :push_bank_account, :push_bin, :push_name, :push_address, :business_app_id, :terminal_id, :transaction_id, :response_code)
    end
end

app/helpers/bank_payments_helper.rb
module BankPaymentsHelper
end

app/views/bank_payments/_form.html.erb
<%= form_for(bank_payment, url: user_bank_payments_path(current_user.id)) do |f| %>
  <% if bank_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bank_payment.errors.count, "error") %> prohibited this bank_payment from being saved:</h2>

      <ul>
      <% bank_payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= f.label :pull_bank_account %>
    <%= f.text_field :pull_bank_account %>
  </div>

  <div class="field">
    <%= f.label :pull_bin %>
    <%= f.text_field :pull_bin %>
  </div>

  <div class="field">
    <%= f.label :debit_exp %>
    <%= f.date_select :debit_exp %>
  </div>

  <div class="field">
    <%= f.label :currency_code %>
    <%= f.text_field :currency_code %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :pull_name %>
    <%= f.text_field :pull_name %>
  </div>

  <div class="field">
    <%= f.label :pull_address %>
    <%= f.text_field :pull_address %>
  </div>

  <div class="field">
    <%= f.label :transaction_time %>
    <%= f.datetime_select :transaction_time %>
  </div>

  <div class="field">
    <%= f.label :push_bank_account %>
    <%= f.text_field :push_bank_account %>
  </div>

  <div class="field">
    <%= f.label :push_bin %>
    <%= f.text_field :push_bin %>
  </div>

  <div class="field">
    <%= f.label :push_name %>
    <%= f.text_field :push_name %>
  </div>

  <div class="field">
    <%= f.label :push_address %>
    <%= f.text_field :push_address %>
  </div>

  <div class="field">
    <%= f.label :business_app_id %>
    <%= f.text_field :business_app_id %>
  </div>

  <div class="field">
    <%= f.label :terminal_id %>
    <%= f.text_field :terminal_id %>
  </div>

  <div class="field">
    <%= f.label :transaction_id %>
    <%= f.text_field :transaction_id %>
  </div>

  <div class="field">
    <%= f.label :response_code %>
    <%= f.text_field :response_code %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bank_payments/edit.html.erb
<h1>Editing Bank Payment</h1>

<%= render 'form', bank_payment: @bank_payment %>

<%= link_to 'Show', @bank_payment %> |
<%= link_to 'Back', user_bank_payments_path %>

app/views/bank_payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bank Payments</h1>

<table>
  <thead>
    <tr>
      <th>Pull bank account</th>
      <th>Pull bin</th>
      <th>Debit exp</th>
      <th>Currency code</th>
      <th>Amount</th>
      <th>Pull name</th>
      <th>Pull address</th>
      <th>Transaction time</th>
      <th>Push bank account</th>
      <th>Push bin</th>
      <th>Push name</th>
      <th>Push address</th>
      <th>Business app</th>
      <th>Terminal</th>
      <th>Transaction</th>
      <th>Response code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_payments.each do |bank_payment| %>
      <tr>
        <td><%= bank_payment.pull_bank_account %></td>
        <td><%= bank_payment.pull_bin %></td>
        <td><%= bank_payment.debit_exp %></td>
        <td><%= bank_payment.currency_code %></td>
        <td><%= bank_payment.amount %></td>
        <td><%= bank_payment.pull_name %></td>
        <td><%= bank_payment.pull_address %></td>
        <td><%= bank_payment.transaction_time %></td>
        <td><%= bank_payment.push_bank_account %></td>
        <td><%= bank_payment.push_bin %></td>
        <td><%= bank_payment.push_name %></td>
        <td><%= bank_payment.push_address %></td>
        <td><%= bank_payment.business_app_id %></td>
        <td><%= bank_payment.terminal_id %></td>
        <td><%= bank_payment.transaction_id %></td>
        <td><%= bank_payment.response_code %></td>
        <td><%= link_to 'Show', bank_payment %></td>
        <td><%= link_to 'Edit', edit_bank_payment_path(bank_payment) %></td>
        <td><%= link_to 'Destroy', bank_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank Payment', new_bank_payment_path %>

app/views/bank_payments/new.html.erb
<h1>New Bank Payment</h1>

<%= render 'form', bank_payment: @bank_payment %>

<%= link_to 'Back', user_bank_payments_path %>

app/views/bank_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pull bank account:</strong>
  <%= @bank_payment.pull_bank_account %>
</p>

<p>
  <strong>Pull bin:</strong>
  <%= @bank_payment.pull_bin %>
</p>

<p>
  <strong>Debit exp:</strong>
  <%= @bank_payment.debit_exp %>
</p>

<p>
  <strong>Currency code:</strong>
  <%= @bank_payment.currency_code %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bank_payment.amount %>
</p>

<p>
  <strong>Pull name:</strong>
  <%= @bank_payment.pull_name %>
</p>

<p>
  <strong>Pull address:</strong>
  <%= @bank_payment.pull_address %>
</p>

<p>
  <strong>Transaction time:</strong>
  <%= @bank_payment.transaction_time %>
</p>

<p>
  <strong>Push bank account:</strong>
  <%= @bank_payment.push_bank_account %>
</p>

<p>
  <strong>Push bin:</strong>
  <%= @bank_payment.push_bin %>
</p>

<p>
  <strong>Push name:</strong>
  <%= @bank_payment.push_name %>
</p>

<p>
  <strong>Push address:</strong>
  <%= @bank_payment.push_address %>
</p>

<p>
  <strong>Business app:</strong>
  <%= @bank_payment.business_app_id %>
</p>

<p>
  <strong>Terminal:</strong>
  <%= @bank_payment.terminal_id %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @bank_payment.transaction_id %>
</p>

<p>
  <strong>Response code:</strong>
  <%= @bank_payment.response_code %>
</p>

<%= link_to 'Edit', edit_bank_payment_path(@bank_payment) %> |
<%= link_to 'Back', bank_payments_path %>