config/routes.rb
Rails.application.routes.draw do


  resources :payments
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :goals
  resources :users do
    # resources :bank_payments
    resources :payments
    resources :pictures
  end

  root 'home#index'
  get 'testpage', to: 'home#tester'
  get 'new_bank_info', to: 'users#edit'
end

app/models/user.rb
class User < ApplicationRecord
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  #  Relationships
  has_many :goals
  has_many :bank_payments
  has_many :pictures
  has_many :payments



  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def instagram
    p "<>"*40
    p "THE ONE"
    p params[:code]
    p"**"*47
    url_builder = "https://api.instagram.com/oauth/access_token/"
    url_builder += "client_id=#{ENV['INSTAGRAM_ID']}&"
    url_builder += "client_secret=#{ENV['INSTAGRAM_SECRET']}&"
    url_builder += "grant_type=authorization_code&"
    url_builder += "redirect_uri=#{ENV['INSTAGRAM_AUTHORIZATION_REDIRECT_URI']}&"
    url_builder += "code=#{params[:code]}"
    response = HTTParty.post url_builder
    p url_builder
    p response
    p "<>"*40
    redirect_to root_path
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  def passthru

  end

  # GET|POST /users/auth/twitter/callback
  def failure
    super
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

  # GET /users/:id.:format
  def show
    # authorize! :read, @user
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end
  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        @user.pull_bank_info = @user.bank_info
        @user.push_bank = @user.bank_info
        @user.push_name = @user.pull_name
        @user.push_address = @user.pull_address
        @user.save

        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      # accessible = [  ] # extend with your own params
      # accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(:name, :email, :bank_info, :pull_bin, :debit_exp, :currency_code, :pull_name, :pull_address, :push_bin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user, html: { multipart: true }) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="row">
    <div class="col-sm-12 col-md-6">
      <center>
        <h4>Account Details</h4>
      </center>
      <div class="form-group">
        <label for="username" class="cols-sm-2 control-label">Image</label>
        <div class="cols-sm-10">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-camera fa" aria-hidden="true"></i></span>
            <input type="file" class="form-control" name="avatar" id="avatar"/>
          </div>
        </div>
      </div>
      <div class="form-group">
    		<label for="name" class="cols-sm-2 control-label">Name</label>
    		<div class="cols-sm-10">
    			<div class="input-group">
    				<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
    				<input type="text" class="form-control" name="name" id="name"  placeholder="Enter your Name" value="<%= user.name %>" />
    			</div>
    		</div>
    	</div>
      <div class="form-group">
    		<label for="email" class="cols-sm-2 control-label">Email</label>
    		<div class="cols-sm-10">
    			<div class="input-group">
    				<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
    				<input type="text" class="form-control" name="email" id="email"  value="<%= user.email %>"/>
    			</div>
    		</div>
    	</div>

    </div><!-- /.col-sm-12 md-6 -->
    <div class="col-sm-12 col-md-6 col-md-offset-3">

      <div class="form-group">
    		<label for="bank_info" class="cols-sm-2 control-label">Bank Name</label>
    		<div class="cols-sm-10">
    			<div class="input-group">
    				<span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
            <%= f.text_field :bank_info, class:'form-control', placeholder:"Bank name..."%>
    			</div>
    		</div>
    	</div>
      <div class="form-group">
        <label for="pull_name" class="cols-sm-2 control-label">Name on Bank Accounts</label>
        <div class="cols-sm-10">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-address-card fa" aria-hidden="true"></i></span>
            <%= f.text_field :pull_name, class:'form-control', placeholder:"User Name on Bank Accounts......"%>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="pull_address" class="cols-sm-2 control-label">Bank Registerd Address</label>
        <div class="cols-sm-10">
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-map-marker fa" aria-hidden="true"></i></span>
            <%= f.text_field :pull_address, class:'form-control', placeholder:"Bank Registered Address..."%>
          </div>
        </div>
      </div>
      <div class="form-group">
    		<label for="push_bank_info" class="cols-sm-2 control-label">Debit Account Number</label>
    		<div class="cols-sm-10">
    			<div class="input-group">
    				<span class="input-group-addon"><i class="fa fa-money fa" aria-hidden="true"></i></span>
            <%= f.text_field :push_bin, class:'form-control', placeholder:"Origin Account..." %>
    			</div>
    		</div>
    	</div>

      <div class="col-sm-12 col-md-6">
        <div class="form-group">

          <label for="debit_exp" class="cols-sm-2 control-label">Expiration Date</label>
          <div class='input-group date' id='datetimepicker1'>
            <%= f.hidden_field :debit_exp, class:'form-control', id:"my_hidden_input" %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-6">
        <div class="form-group">
          <label for="currency_code" class="cols-sm-2 control-label">Currency Code</label>
            <div class='input-group date' id='currency_code'>
            <%= select_tag(:currency_code, options_for_select([['USD', "USD"], ['EU', "EU"], ["CAD", "CAD"] ] ), class:"form-control") %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-usd"></span>
            </span>
          </div>
        </div>
      </div><!-- /.col-sm-12 col-md-6 -->

      <div class="form-group">
    		<label for="username" class="cols-sm-2 control-label">Destination Account Number</label>
    		<div class="cols-sm-10">
    			<div class="input-group">
    				<span class="input-group-addon"><i class="fa fa-money fa" aria-hidden="true"></i></span>
            <%= f.text_field :pull_bin, class:'form-control', placeholder:"Destination Account..." %>

    			</div>
    		</div>
    	</div>

      <%= f.submit "Save", class: "btn btn-block btn-success" %>

    </div><!-- /.col-sm-12 col-md-6 -->
    <div class="col-sm-12">
    </div><!-- /.col-sm-12 -->

  </div><!-- /.row -->

<% end %>


<script type="text/javascript">
  $(function () {
      $('#datetimepicker1').datetimepicker();
      $('#datepicker').on('changeDate', function() {
          $('#my_hidden_input').val(
              $('#datepicker').datepicker('getFormattedDate')
          );
      });
  });

</script>

app/views/users/edit.html.erb
<center><h1>Bank Information</h1></center>

<%= render 'form', user: @user %>

<% link_to 'Show', @user %> |
<% link_to 'Back', users_path %>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<div>

</div>

<%= link_to "add/edit bank info", edit_user_path(@user) %>

<% if true %>
  <p>
    <%= image_tag @user.pictures.last.picture.url %>

  </p>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |